### PR TITLE
Add direnv support

### PR DESCRIPTION
**Pull request by voelzmo**
Instead of exporting the GOPATH env variable all the time by hand
let direnv do the heavy lifting

### CODE REVIEW

**Comment by ematpl** [comment]
Hi, @voelzmo,

Thanks for the contribution. Does SAP have an org for you to publicize membership in to satisfy Dreddbot's CLA check?

In the meantime, we have a couple suggestions on the PR. First, could you have the `.envrc` file set the GOPATH directly, instead of using the direnv feature? This would allow users to set the GOPATH by sourcing the `.envrc` file even if they don't have direnv installed, and is something we've [already done for diego-release](https://github.com/cloudfoundry-incubator/diego-release/blob/develop/.envrc). Also, for the README update, I think you have to run `direnv allow` in the directory with the `.envrc` file to allow it to alter your environment. Again, this is something we've [documented in the diego-release README](https://github.com/cloudfoundry-incubator/diego-release#-initial-setup).

Thanks,
Eric, for the CF Runtime Diego team

**Comment by voelzmo** [comment]
@ematpl Thanks for the nice suggestions, I wasn't aware that the diego-release readme was such a nice example ;)

As far as I know the SAP Cloudfoundry github organization is still in the making, I'd expect it to manifest within the next few weeks - hopefully sooner than later.

**Comment by ematpl** [comment]
@voelzmo: Thanks for the changes! Looks great. Once the correct org for the CLA is worked out, we'll pull it in.

**Comment by voelzmo** [comment]
@ematpl I got notified on Friday that the CLA has been worked out. Can we restart the @cfdreddbot to see if he is recognizing this as well? ;)

**Comment by ematpl** [comment]
@voelzmo: Let me try closing and re-opening this PR. Dreddbot should re-judge you then. :)

**Pull request merged**
